## Importing Libraries

In [512]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

## Importing the datasets

In [513]:
data = r"C:\NYABUTO\DATA ANALYTICS\MACHINE LEARNING PROJECT\Capstone\Data\\"

branches = pd.read_csv(data + "branches.csv")
products = pd.read_csv(data + "products.csv")
customers = pd.read_csv(data + "customers.csv")
promos = pd.read_csv(data + "promos.csv")
transactions = pd.read_csv(data + "transactions.csv")
receipt_lines = pd.read_csv(data + "receipt-lines.csv")
inflation = pd.read_csv(data + "inflation_data_knbs.csv")
holidays = pd.read_csv(data + "holidays_kenya.csv")

## Performing basic data checks for the datasets

In [514]:
# Putting relevant datasets in dictionary
datasets = {"Products": products, "Customers": customers,
            "Promotions": promos, "Transactions": transactions,
            "Receipt Lines": receipt_lines, "Inflation": inflation,
             "Holidays": holidays, "Branches": branches}

In [515]:
# Funciton to perform basic data checks
def data_summary(df):
    print(f"Dataset summary:\n{df.shape}")
    print("=" * 50)
    print("Duplicates:", df.duplicated().sum())
    print("=" * 50)
    print("Columns:\n", df.columns.tolist())
    print("=" * 50)
    df.info()
    print("=" * 50)
    print("Missing Values")
    missing = pd.DataFrame({"Value Count": df.isna().sum(),
        "Percentage": (df.isna().sum() / len(df) * 100)})
    print(missing[missing["Value Count"] > 0])
    print("=" * 50)
    print("Numeric Summary")
    display(df.describe().T)
    print("=" * 50)
    print("Categorical Summary")
    display(df.describe(include=["object", "str"]).T)

In [516]:
# looping through datasets to call the function
for name, dataset in datasets.items():
    print(f"{name} Data")
    data_summary(dataset)

Products Data
Dataset summary:
(171, 6)
==================================================
Duplicates: 0
==================================================
Columns:
 ['product_id', 'product_name', 'category', 'tier', 'list_price_kes', 'unit_cost_kes']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      171 non-null    str
 1   product_name    171 non-null    str
 2   category        171 non-null    str
 3   tier            171 non-null    str
 4   list_price_kes  171 non-null    int64
 5   unit_cost_kes   165 non-null    float64
dtypes: float64(1), int64(1), str(4)
memory usage: 8.1 KB
==================================================
Missing Values
               Value Count  Percentage
unit_cost_kes            6    3.508772
==================================================
Numeric Summary

,count,mean,std,min,25%,50%,75%,max
list_price_kes,171.0,270.269006,251.882718,16.00,109.00,189.0,339.00,1409.00
unit_cost_kes,165.0,217.652000,209.705897,12.18,88.18,152.7,271.78,1231.66

==================================================
Categorical Summary

             count unique              top freq
product_id     171    171          SKU0001    1
product_name   171     93  Maize Flour 2kg    3
category       171      9     Food Staples   47
tier           171      3         Standard   93

Customers Data
Dataset summary:
(8222, 7)
==================================================
Duplicates: 0
==================================================
Columns:
 ['customer_id', 'registration_date', 'registration_store_id', 'county', 'age_band', 'gender', 'phone_hash']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 8222 entries, 0 to 8221
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            8222 non-null   str
 1   registration_date      8222 non-null   str
 2   registration_store_id  8222 non-null   str
 3   county                 8103 non-null   str
 4   age_band               7796 non-null   str
 5   gender                 7923 non-null   str
 6   phone_hash             8222 non-null   str
dtypes: str(7)
memory usage: 449.8 KB
==================================================
Missing Values
          Value Count  Percentage
county            119    1.447336
age_band          426    5.181221
gender            299    3.636585
==================================================
Numeric Summary

                      count unique          top  freq
customer_id            8222   8222      C000001     1
registration_date      8222   1771  19-Jan-2023    13
registration_store_id  8222     10          S03  2030
county                 8103      9      Nairobi  4249
age_band               7796      7        25-34  2245
gender                 7923      4       Female  4433
phone_hash             8222   8222     7dd2b756     1

==================================================
Categorical Summary

                      count unique          top  freq
customer_id            8222   8222      C000001     1
registration_date      8222   1771  19-Jan-2023    13
registration_store_id  8222     10          S03  2030
county                 8103      9      Nairobi  4249
age_band               7796      7        25-34  2245
gender                 7923      4       Female  4433
phone_hash             8222   8222     7dd2b756     1

Promotions Data
Dataset summary:
(322, 10)
==================================================
Duplicates: 0
==================================================
Columns:
 ['promo_id', 'promo_name', 'promo_type', 'start_date', 'end_date', 'scope_type', 'category', 'product_id', 'store_scope', 'discount_pct']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   promo_id      322 non-null    str
 1   promo_name    322 non-null    str
 2   promo_type    322 non-null    str
 3   start_date    322 non-null    str
 4   end_date      322 non-null    str
 5   scope_type    322 non-null    str
 6   category      82 non-null     str
 7   product_id    240 non-null    str
 8   store_scope   322 non-null    str
 9   discount_pct  322 non-null    int64
dtypes: int64(1), str(9)
memory usage: 25.3 KB
==================================================
Missing Values
            Value Count  Percentage
category            240   74.534161
product_id           82   25.465839
==================================================
Numeric Summary

              count       mean        std  min   25%   50%   75%   max
discount_pct  322.0  18.099379  10.647689  5.0  10.0  20.0  25.0  40.0

==================================================
Categorical Summary

            count unique                   top freq
promo_id      322    322                PR0001    1
promo_name    322      6      Weekly SKU Offer  240
promo_type    322      1        Percentage off  322
start_date    322    242           29-Nov-2024    9
end_date      322    237           02-Dec-2024   10
scope_type    322      2                   SKU  240
category       82      9  Household & Cleaning   14
product_id    240    113               SKU0066    7
store_scope   322     98                   ALL  218

Transactions Data
Dataset summary:
(435951, 9)
==================================================
Duplicates: 0
==================================================
Columns:
 ['transaction_id', 'transaction_date', 'transaction_time', 'store_id', 'customer_id', 'basket_total_kes', 'payment_method', 'payment_reference', 'original_transaction_id']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 435951 entries, 0 to 435950
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   transaction_id           435951 non-null  str
 1   transaction_date         435951 non-null  str
 2   transaction_time         435951 non-null  str
 3   store_id                 435951 non-null  str
 4   customer_id              435951 non-null  str
 5   basket_total_kes         435951 non-null  float64
 6   payment_method           435467 non-null  str
 7   payment_reference        227019 non-null  str
 8   original_transaction_id  5199 non-null    str
dtypes: float64(1), str(8)
memory usage: 29.9 MB
==================================================
Missing Values
                         Value Count  Percentage
payment_method                   484    0.111022
payment_reference             208932   47.925570
original_transaction_id       430752   98.807435
==================================================
Numeric Summary

,count,mean,std,min,25%,50%,75%,max
basket_total_kes,435951.0,1583.594652,2034.385745,-14421.0,455.3,1043.6,2070.955,113114.8

==================================================
Categorical Summary

                          count  unique                 top    freq
transaction_id           435951  435951  S01-20241001-00001       1
transaction_date         435951     730         29-Nov-2025    1403
transaction_time         435951     840            06:43 PM    1070
store_id                 435951      10                 S03  108347
customer_id              435951    8196             C002162     269
payment_method           435467       5              M-Pesa  226630
payment_reference        227019  227019          WUWDMLZE82       1
original_transaction_id    5199    5199  S01-20241004-00062       1

Receipt Lines Data
Dataset summary:
(2175508, 7)
==================================================
Duplicates: 0
==================================================
Columns:
 ['line_id', 'transaction_id', 'product_id', 'quantity', 'unit_price_kes', 'discount_pct', 'promo_id']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 2175508 entries, 0 to 2175507
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   line_id         int64
 1   transaction_id  str
 2   product_id      str
 3   quantity        int64
 4   unit_price_kes  str
 5   discount_pct    int64
 6   promo_id        str
dtypes: int64(3), str(4)
memory usage: 116.2 MB
==================================================
Missing Values
          Value Count  Percentage
promo_id      1761885   80.987291
==================================================
Numeric Summary

,count,mean,std,min,25%,50%,75%,max
line_id,2175508.0,1.087754e+06,628015.209050,1.0,543877.75,1087754.5,1631631.25,2175508.0
quantity,2175508.0,1.740819e+00,1.689856,-69.0,1.00,1.0,2.00,96.0
discount_pct,2175508.0,2.808885e+00,6.778290,0.0,0.00,0.0,0.00,40.0

==================================================
Categorical Summary

                  count  unique                 top    freq
transaction_id  2175508  435951  S09-20260227-00014      47
product_id      2175508     171             SKU0010   62074
unit_price_kes  2175508     284                  69  143036
promo_id         413623     318              PR0322   10692

Inflation Data
Dataset summary:
(24, 3)
==================================================
Duplicates: 0
==================================================
Columns:
 ['month', 'inflation_12m_pct', 'annual_avg_inflation_pct']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   month                     24 non-null     str
 1   inflation_12m_pct         24 non-null     float64
 2   annual_avg_inflation_pct  24 non-null     float64
dtypes: float64(2), str(1)
memory usage: 708.0 bytes
==================================================
Missing Values
Empty DataFrame
Columns: [Value Count, Percentage]
Index: []
==================================================
Numeric Summary

,count,mean,std,min,25%,50%,75%,max
inflation_12m_pct,24.0,4.534167,1.255759,2.72,3.7175,4.395,4.8325,6.76
annual_avg_inflation_pct,24.0,4.265000,0.586723,3.55,3.7850,4.185,4.6975,5.44

==================================================
Categorical Summary

      count unique         top freq
month    24     24  01/10/2024    1

Holidays Data
Dataset summary:
(27, 2)
==================================================
Duplicates: 0
==================================================
Columns:
 ['date', 'holiday_name']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          27 non-null     str
 1   holiday_name  27 non-null     str
dtypes: str(2)
memory usage: 564.0 bytes
==================================================
Missing Values
Empty DataFrame
Columns: [Value Count, Percentage]
Index: []
==================================================
Numeric Summary

             count unique            top freq
date            27     27     2024-10-10    1
holiday_name    27     15  Mazingira Day    2

==================================================
Categorical Summary

             count unique            top freq
date            27     27     2024-10-10    1
holiday_name    27     15  Mazingira Day    2

Branches Data
Dataset summary:
(10, 8)
==================================================
Duplicates: 0
==================================================
Columns:
 ['store_id', 'store_name', 'county', 'town', 'format', 'store_positioning', 'opening_date', 'floor_area_sqm']
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   store_id           10 non-null     str
 1   store_name         10 non-null     str
 2   county             10 non-null     str
 3   town               10 non-null     str
 4   format             10 non-null     str
 5   store_positioning  10 non-null     str
 6   opening_date       10 non-null     str
 7   floor_area_sqm     10 non-null     int64
dtypes: int64(1), str(7)
memory usage: 772.0 bytes
==================================================
Missing Values
Empty DataFrame
Columns: [Value Count, Percentage]
Index: []
==================================================
Numeric Summary

,count,mean,std,min,25%,50%,75%,max
floor_area_sqm,10.0,1830.0,988.601706,650.0,1000.0,2000.0,2150.0,3900.0

==================================================
Categorical Summary

                  count unique                   top freq
store_id             10     10                   S01    1
store_name           10     10  Kilimani Supermarket    1
county               10      5               Nairobi    4
town                 10     10              Kilimani    1
format               10      3           Supermarket    6
store_positioning    10      3                 Value    4
opening_date         10     10           01-Jun-2017    1

## Data Cleaning

In [517]:
#  before counts showing row-count in each dataframe before the cleaning.

before_count = {name: len(dataset) for name, dataset in datasets.items()}
display(before_count)

{'Products': 171,
 'Customers': 8222,
 'Promotions': 322,
 'Transactions': 435951,
 'Receipt Lines': 2175508,
 'Inflation': 24,
 'Holidays': 27,
 'Branches': 10}

## 1. Correcting Data Types

### Date Columns

- Dates are stored as text, and some datasets have different date formats

In [518]:
# Dictionary for the date columns, with date formats
date_columns = {"Branches": {"opening_date": "%d-%b-%Y"},
                "Customers": {"registration_date": "%d-%b-%Y"},
                "Promotions": {"start_date": "%d-%b-%Y", "end_date": "%d-%b-%Y"},
                "Transactions": {"transaction_date": "%d-%b-%Y"},
                "Inflation": {"month": "%d/%m/%Y"},
                "Holidays": {"date": "%Y-%m-%d"}}

In [ ]:
# Looping through dictionary to convert data types
for name, columns in date_columns.items():
    for column, date_format in columns.items():
        datasets[name][column] = pd.to_datetime(
            datasets[name][column], format = date_format, errors = "coerce")

In [ ]:
# Time column (Stored as text, with AM/PM)
transactions["transaction_time"] = pd.to_datetime(
    transactions["transaction_time"], format="%I:%M %p",errors="coerce").dt.time

### Numeric variables passed as text

- Some unit prices in recepit lines are written with comma, and currency "KES"

In [521]:
# Inspecting the column
receipt_lines["unit_price_kes"].unique()

<StringArray>
[      '129',        '89',       '109',       '169',        '69',        '79',
       '219',       '349',    'KES 89',        '16',
 ...
 'KES 1,269',      '1299',      '1499',       '699', 'KES 1,499',      '1509',
   'KES 679', 'KES 1,509',      '1309',      '1319']
Length: 284, dtype: str

In [ ]:
# Removig the KES text and comma, then converting to numeric
receipt_lines["unit_price_kes"] = pd.to_numeric(
    receipt_lines["unit_price_kes"].str.replace(r"KES |,", "", regex=True).str.strip(), errors="coerce")

### Text variables stored as numeric

- The line_id in receipt lines is a label, therefore cannot be used for calculations

In [523]:
receipt_lines["line_id"] = receipt_lines["line_id"].astype("string")

## 2. Standardizing Categorical variables values

- Listing values of each text column to spot any variations of values or placeholders

In [ ]:
# Creating variable for categorical columns
for name, dataset in datasets.items():
    categorical_columns = dataset.select_dtypes(include = ["object", "str"]).columns
    for column in categorical_columns:
        if column.endswith("_id"): # excludes ID columns, they are all unique
            continue
        
        print(f"\n{name} - {column}")
        print(dataset[column].value_counts(dropna=False))

Products - product_name
product_name
Maize Flour 2kg          3
Pishori Rice 2kg         3
Wheat Flour 2kg          3
Cooking Oil 1L           3
Loose Tea Leaves 250g    3
                        ..
Baby Soap                1
Exercise Book 200pg      1
Ball Pens Box of 12      1
Geometry Set             1
Crayons 12 Colours       1
Name: count, Length: 93, dtype: int64

Products - category
category
Food Staples              47
Personal Care             21
Dairy                     18
Beverages                 18
Snacks & Confectionery    18
Household & Cleaning      17
Farm Produce              12
School & Stationery       11
Baby Care                  9
Name: count, dtype: int64

Products - tier
tier
Standard    93
Economy     40
Premium     38
Name: count, dtype: int64

Customers - county
county
Nairobi      4249
Kiambu       1795
Machakos      866
Kajiado       808
Nakuru        231
NaN           119
unknown        68
-              49
Baringo        24
Nyandarua      13
Name: count, dtype: int64

Customers - age_band
age_band
25-34      2245
35-44      1824
45-54      1357
55+        1036
18-24       878
NaN         426
unknown     278
-           178
Name: count, dtype: int64

Customers - gender
gender
Female     4433
Male       3174
NaN         299
unknown     186
-           130
Name: count, dtype: int64

Customers - phone_hash
phone_hash
7dd2b756    1
f3db473b    1
95625cdf    1
f9648e92    1
b3ef294f    1
           ..
0c9fa52f    1
5bb83d2c    1
f6805723    1
926681e5    1
8c6e5ec6    1
Name: count, Length: 8222, dtype: int64

Promotions - promo_name
promo_name
Weekly SKU Offer    240
Payday Deals         48
Black Friday         18
Back to School        6
Easter Offers         6
Festive Season        4
Name: count, dtype: int64

Promotions - promo_type
promo_type
Percentage off    322
Name: count, dtype: int64

Promotions - scope_type
scope_type
SKU         240
Category     82
Name: count, dtype: int64

Promotions - category
category
NaN                       240
Household & Cleaning       14
Snacks & Confectionery     14
Personal Care              14
Beverages                  13
Food Staples                9
School & Stationery         8
Dairy                       4
Farm Produce                4
Baby Care                   2
Name: count, dtype: int64

Promotions - store_scope
store_scope
ALL                        218
S02;S05;S07                  2
S01;S02;S04;S05;S07;S08      2
S01;S02;S03;S06;S08;S10      2
S01;S02;S03;S04;S07          2
                          ...
S02;S08;S09                  1
S03;S05;S08                  1
S02;S05;S06;S10              1
S02;S05;S08                  1
S01;S04;S09                  1
Name: count, Length: 98, dtype: int64

Transactions - transaction_time
transaction_time
18:43:00    1070
18:14:00    1069
18:44:00    1068
18:17:00    1059
18:38:00    1055
            ...
07:57:00     132
07:22:00     131
07:07:00     130
07:23:00     130
07:39:00     130
Name: count, Length: 840, dtype: int64

Transactions - payment_method
payment_method
M-Pesa     226630
Cash       127183
Card        81404
NaN           484
-             130
unknown       120
Name: count, dtype: int64

Transactions - payment_reference
payment_reference
NaN           208932
WUWDMLZE82         1
WD3AG3SLYX         1
SBV5FFSJ9D         1
T4KZ6AW4KD         1
               ...
QWR72VXF52         1
X5DFS6P435         1
SHLFL3R5EZ         1
WU1YAFNRJ4         1
X6LUHM1M6B         1
Name: count, Length: 227020, dtype: int64

Holidays - holiday_name
holiday_name
Mazingira Day                     2
Mashujaa Day                      2
Jamhuri Day                       2
Christmas Day                     2
Boxing Day (Utamaduni Day)        2
New Year's Day                    2
Idd-ul-Fitr                       2
Good Friday                       2
Easter Monday                     2
Labour Day                        2
Madaraka Day                      2
Idd-ul-Azha                       2
Mashujaa Day (observed Monday)    1
Madaraka Day (observed Monday)    1
State Mourning Holiday            1
Name: count, dtype: int64

Branches - store_name
store_name
Kilimani Supermarket         1
Eastleigh Supermarket        1
Embakasi Hypermarket         1
Karen Express                1
Ruiru Supermarket            1
Kikuyu Express               1
Thika Supermarket            1
Athi River Supermarket       1
Ongata Rongai Supermarket    1
Naivasha Express             1
Name: count, dtype: int64

Branches - county
county
Nairobi     4
Kiambu      3
Machakos    1
Kajiado     1
Nakuru      1
Name: count, dtype: int64

Branches - town
town
Kilimani         1
Eastleigh        1
Embakasi         1
Karen            1
Ruiru            1
Kikuyu           1
Thika            1
Athi River       1
Ongata Rongai    1
Naivasha         1
Name: count, dtype: int64

Branches - format
format
Supermarket    6
Express        3
Hypermarket    1
Name: count, dtype: int64

Branches - store_positioning
store_positioning
Value         4
Mid-market    4
Upmarket      2
Name: count, dtype: int64

### Place holders

#### Placeholders

- There are 4 different ways of the values that are missing in multiple columns (`unknown`,`-`,`N/A`,blank)

In [ ]:
# In customer data, 3 columns have all these placeholders
customers = datasets["Customers"]
for column in ["county","age_band","gender"]:
    customers[column] =  customers[column].astype("str").str.strip()
    customers[column] = customers[column].replace(
        r"^-|^unknown$|^n/a$|^$", pd.NA, regex=True).fillna("unknown")

In [550]:
# Transactions
# Converting placeholders to blank
transactions = datasets["Transactions"]
transactions["payment_method"] = transactions[
    "payment_method"].replace(["unknown","-"], pd.NA)

## 3. Handling Missing Values

In [ ]:
# Displaying all the missing values
for name, dataset in datasets.items():
    missing = dataset.isna().sum()
    missing = missing[missing > 0]
    
    if not missing.empty:
        print(f"\n{name}")
        display(pd.DataFrame({"Percentage of Missing": (missing / len(dataset)*100).round(2)}))

Products

               Percentage of Missing
unit_cost_kes                   3.51

Promotions

            Percentage of Missing
category                    74.53
product_id                  25.47

Transactions

                         Percentage of Missing
payment_method                            0.17
payment_reference                        47.93
original_transaction_id                  98.81

Receipt Lines

          Percentage of Missing
promo_id                  80.99

In [528]:
# Products
display(products[products["unit_cost_kes"].isna()])

,product_id,product_name,category,tier,list_price_kes,unit_cost_kes
45,SKU0046,Muesli 500g,Food Staples,Standard,479,NaN
55,SKU0056,Margarine 500g,Dairy,Standard,249,NaN
93,SKU0094,Sparkling Water 500ml,Beverages,Standard,109,NaN
99,SKU0100,Potato Crisps,Snacks & Confectionery,Standard,59,NaN
103,SKU0104,Chocolate Bar,Snacks & Confectionery,Premium,119,NaN
140,SKU0141,Body Lotion 400ml,Personal Care,Standard,349,NaN

- Missing product unit cost will be filled with the category's median cost-to-price ratio
- For cleaning purposes, this is included here, but for modelling, this will be done after splitting data, to prevent test-train leakage

In [ ]:
cost_ratio = (products["unit_cost_kes"]/products["list_price_kes"])
products["unit_cost_kes"] = products["unit_cost_kes"].fillna(
    products["list_price_kes"] * cost_ratio.groupby(
        products["category"]).transform("median")).round(2)

In [530]:
# Promotions
# Confirming entries where product_id and category are either both missing/both populated(Promotions are either on a specific product or specific category).
promos[promos["category"].isna() == promos["product_id"].isna()].shape[0]

0

##### Payment method in Transactions

- Becuase payment reference is **only** available for M-Pesa payments, missing payment methods with payment reference are automatically M-Pesa

In [531]:
# Confirming entries with missing payment method that have payment reference
missing_method = transactions["payment_method"].isna() 
has_reference = transactions["payment_reference"].notna()
print(f"Has References & Missing payment method: {(missing_method & has_reference).sum()}")

Has References & Missing payment method: 389

In [532]:
# The 389 records are imputed with M-Pesa as payment method
transactions.loc[missing_method & has_reference,"payment_method"] = "M-Pesa"

In [533]:
# Converting the remaining missing values to unknown, there's no way of guessing accurately
transactions["payment_method"] = transactions["payment_method"].fillna("unknown")

In [ ]:
# Confirming no payment reference exist for non M-Pesa payment
reference_no_mpesa = ((transactions["payment_method"] 
                       != "M-Pesa") & transactions["payment_reference"].notna()).sum()
print(f"Payment with reference but not Mpesa payment method: {reference_no_mpesa}")

Payment with reference but not Mpesa payment method: 0

In [ ]:
# Transactions
# Only returned receipts(with negative amounts) should have original_transaction_id
with_return = transactions["basket_total_kes"]<0
with_org_id = transactions["original_transaction_id"].notna()
print(f"Mismatch: {(with_org_id != with_return).sum()}")

Mismatch: 0

In [536]:
# Receipt lines
# Checking missing promo ID ( Missing promo_id values should have a discount_pct of 0, meaning no promo was offered)
receipt_lines[receipt_lines["promo_id"].isna()]["discount_pct"].value_counts()

discount_pct
0    1761885
Name: count, dtype: int64

## 4. Investigating outliers

In [ ]:
# Create a numeric columns variable
for name, dataset in datasets.items():
    numeric_variables = dataset.select_dtypes(include="number")
    print(f"\n{name}")
    
    if len(numeric_variables.columns):
        display(numeric_variables.describe().T)
    else:
        print("No numeric columns in dataset.")

Products

,count,mean,std,min,25%,50%,75%,max
list_price_kes,171.0,270.269006,251.882718,16.00,109.00,189.0,339.000,1409.00
unit_cost_kes,171.0,216.440117,207.474928,12.18,88.06,152.7,269.655,1231.66

Customers
No numeric columns in dataset.

Promotions

              count       mean        std  min   25%   50%   75%   max
discount_pct  322.0  18.099379  10.647689  5.0  10.0  20.0  25.0  40.0

Transactions

,count,mean,std,min,25%,50%,75%,max
basket_total_kes,435951.0,1583.594652,2034.385745,-14421.0,455.3,1043.6,2070.955,113114.8

Receipt Lines

,count,mean,std,min,25%,50%,75%,max
quantity,2175508.0,1.740819,1.689856,-69.0,1.0,1.0,2.0,96.0
unit_price_kes,2175508.0,193.312708,173.986652,16.0,89.0,139.0,249.0,1509.0
discount_pct,2175508.0,2.808885,6.778290,0.0,0.0,0.0,0.0,40.0

Inflation

,count,mean,std,min,25%,50%,75%,max
inflation_12m_pct,24.0,4.534167,1.255759,2.72,3.7175,4.395,4.8325,6.76
annual_avg_inflation_pct,24.0,4.265000,0.586723,3.55,3.7850,4.185,4.6975,5.44

Holidays
No numeric columns in dataset.

Branches

,count,mean,std,min,25%,50%,75%,max
floor_area_sqm,10.0,1830.0,988.601706,650.0,1000.0,2000.0,2150.0,3900.0

In [ ]:
# Using the IQR rule to check outliers

all_outliers = []
for name, dataset in datasets.items():
    numeric_variables = dataset.select_dtypes(include="number")

    for column in numeric_variables.columns:
        data = numeric_variables[column].dropna()
        Q1 = data.quantile(0.25)
        Q3 = data.quantile(0.75)
        IQR = Q3-Q1
        lower_limit = Q1 - (IQR * 1.5)
        upper_limit = Q3 + (IQR * 1.5)

        outliers = data[(data < lower_limit)|(data > upper_limit)]
        all_outliers.append({"Dataset": name,
                            "Column": column,
                            "Outliers(%)": round(len(outliers)/len(data)*100, 2)})
        
display(pd.DataFrame(all_outliers))

[{'Dataset': 'Products', 'Column': 'list_price_kes', 'Outliers(%)': 7.6},
 {'Dataset': 'Products', 'Column': 'unit_cost_kes', 'Outliers(%)': 8.19},
 {'Dataset': 'Promotions', 'Column': 'discount_pct', 'Outliers(%)': 0.0},
 {'Dataset': 'Transactions',
  'Column': 'basket_total_kes',
  'Outliers(%)': 5.81},
 {'Dataset': 'Transactions', 'Column': 'year', 'Outliers(%)': 0.0},
 {'Dataset': 'Transactions', 'Column': 'month', 'Outliers(%)': 0.0},
 {'Dataset': 'Transactions', 'Column': 'week', 'Outliers(%)': 0.0},
 {'Dataset': 'Receipt Lines', 'Column': 'quantity', 'Outliers(%)': 7.54},
 {'Dataset': 'Receipt Lines', 'Column': 'unit_price_kes', 'Outliers(%)': 3.92},
 {'Dataset': 'Receipt Lines', 'Column': 'discount_pct', 'Outliers(%)': 19.01},
 {'Dataset': 'Inflation', 'Column': 'inflation_12m_pct', 'Outliers(%)': 12.5},
 {'Dataset': 'Inflation',
  'Column': 'annual_avg_inflation_pct',
  'Outliers(%)': 0.0},
 {'Dataset': 'Branches', 'Column': 'floor_area_sqm', 'Outliers(%)': 10.0}]

In [ ]:
# Investigating outliers in each column, to decide what to do with them (Retain or drop)
# Receipt lines
print("Discount <0 or >100:",
      ((receipt_lines["discount_pct"] < 0)|
       (receipt_lines["discount_pct"] > 100)).sum())
print("Negative unit prices:", (receipt_lines["unit_price_kes"] < 0).sum())
print("Zero unit prices:", (receipt_lines["unit_price_kes"] == 0).sum())
print("Negative quantities:", (receipt_lines["quantity"] < 0).sum())
print("Zero quantities:", (receipt_lines["quantity"] == 0).sum())

Discount <0 or >100: 0
Negative unit prices: 0
Zero unit prices: 0
Negative quantities: 5199
Zero quantities: 0

In [540]:
# Products
for column in ["list_price_kes", "unit_cost_kes"]:
    print(f"\n{column}")
    print("Negative values:", (products[column] < 0).sum())
    print("Zero values:", (products[column] == 0).sum())

list_price_kes
Negative values: 0
Zero values: 0

unit_cost_kes
Negative values: 0
Zero values: 0

In [541]:
# Transactions
# Negative transactions indicate return transactions
print("Negative transaction totals:",
      (transactions["basket_total_kes"] < 0).sum())
print("Zero transaction totals:",
      (transactions["basket_total_kes"] == 0).sum())

Negative transaction totals: 5199
Zero transaction totals: 0

- Flagged columns are all retained, no entries are dropped, as the inspection found all the entries to be valid/realistic

## 5. Feature Engineering

- The model forecasts weekly and monthly forecasts for the 3 targets, grouped by store branch and product category: **sales revenue**, **units sold**, and **transaction volume**.
- Selected features include: year, month, end_month_indicator, store branch, product category, store floor area, promotion indicator, discount percentage and inflation rate.
- Targets use ordinary sales, therefore returns/refunds are not included
-Revenue is defined as `quantity * unit price * (1-discount/100)`

### Time Features

In [542]:
# Extracting time-based features from transaction dates
transactions["year"] = transactions["transaction_date"].dt.year
transactions["month"] = transactions["transaction_date"].dt.month
transactions["week"] = transactions["transaction_date"].dt.isocalendar().week
transactions["day_name"] = transactions["transaction_date"].dt.day_name()
transactions["end_month"] = transactions["transaction_date"].dt.is_month_end

### Preparing sales data

In [552]:
#Excluding returns, they are not included in the model
sales = receipt_lines[receipt_lines["quantity"]>0].copy() #new sales df

#Adding transaction dates, store and time features
sales = sales.merge(transactions[["transaction_id", "transaction_date","year", "month", 
                                  "week","day_name","end_month",  "store_id"]], 
                                  on = "transaction_id", how = "left")
# Adding product category
sales = sales.merge(products[["product_id", "category"]], 
                    on = "product_id", how = "left")

# Adding a revenue column
sales["revenue_kes"] = (sales["quantity"] * sales["unit_price_kes"] * 
                        (1-sales["discount_pct"] /100))

# To be able to do weekly forecast, we need to determine start of each week
sales["week_start"] = (sales["transaction_date"]-
                       pd.to_timedelta(sales["transaction_date"].dt.day_of_week, unit = "D"))

# Identify sales linked to a promo
sales["promo_indicator"] = sales["promo_id"].notna().astype(int)

# Identifying sales linked to a holiday
sales["is_holiday"] = sales["transaction_date"].isin(holidays["date"]).astype(int)

In [553]:
sales.head()

,line_id,transaction_id,product_id,quantity,unit_price_kes,discount_pct,promo_id,transaction_date,year,month,week,day_name,end_month,store_id,category,revenue_kes,week_start,promo_indicator,is_holiday
0,1,S01-20241001-00001,SKU0058,1,129,0,NaN,2024-10-01,2024,10,40,Tuesday,False,S01,Dairy,129.0,2024-09-30,0,0
1,2,S01-20241001-00001,SKU0020,2,89,0,NaN,2024-10-01,2024,10,40,Tuesday,False,S01,Food Staples,178.0,2024-09-30,0,0
2,3,S01-20241001-00001,SKU0136,1,109,0,NaN,2024-10-01,2024,10,40,Tuesday,False,S01,Personal Care,109.0,2024-09-30,0,0
3,4,S01-20241001-00001,SKU0059,1,169,0,NaN,2024-10-01,2024,10,40,Tuesday,False,S01,Dairy,169.0,2024-09-30,0,0
4,5,S01-20241001-00001,SKU0092,1,69,0,NaN,2024-10-01,2024,10,40,Tuesday,False,S01,Beverages,69.0,2024-09-30,0,0

### Aggregating sales - To enable weekly and monthly forecasting

1. Weekly

In [ ]:
# Aggregate sales by week, store and product category.
weekly_data = sales.groupby(
    ["week_start", "store_id", "product_id", "category"], as_index = False).agg(
       revenue_kes=("revenue_kes", "sum"), units_sold=(
          "quantity", "sum"),transaction_count=("transaction_id", "nunique"),promotion_indicator=(
             "promo_indicator", "max"), is_holiday=("is_holiday", "max"), discount_pct=("discount_pct", "mean"))

# Adding time features to weekly dataset

weekly_data["year"] = weekly_data["week_start"].dt.year
weekly_data["month"] = weekly_data["week_start"].dt.month

week_end = weekly_data["week_start"] + pd.Timedelta(days=6)
weekly_data["end_month_indicator"] = (week_end.dt.is_month_end
    | (weekly_data["week_start"].dt.month != week_end.dt.month)).astype(int)

# Adding the inflation rate based on the week start month.
inflation_by_month = inflation.set_index(
   inflation["month"].dt.to_period("M"))["inflation_12m_pct"]

weekly_data["inflation_12m_pct"] = weekly_data[
   "week_start"].dt.to_period("M").map(inflation_by_month)

# Adding lag features (For previous week sales)
weekly_data = weekly_data.sort_values(["store_id", "product_id", "week_start"])

for column in ["revenue_kes", "units_sold", "transaction_count"]:
   weekly_data[f"previous_{column}"] = (weekly_data.groupby(
      ["store_id", "product_id"])[column].shift(1))

2. Monthly

In [ ]:
# Assigning each sale to month.
sales["month_start"] = (sales["transaction_date"].dt.to_period("M").dt.to_timestamp())

monthly_data = sales.groupby(
    ["month_start", "store_id", "product_id", "category"],as_index = False).agg(
       revenue_kes=("revenue_kes", "sum"), units_sold=(
           "quantity", "sum"),transaction_count=("transaction_id", "nunique"),promotion_indicator=(
               "promo_indicator", "max"), is_holiday=("is_holiday", "max"), discount_pct=("discount_pct", "mean"))

# Adding time features 
monthly_data["year"] = monthly_data["month_start"].dt.year
monthly_data["month"] = monthly_data["month_start"].dt.month

# Add the monthly inflation ratate.
inflation_by_month = inflation.set_index(
    inflation["month"].dt.to_period("M"))["inflation_12m_pct"]
monthly_data["inflation_12m_pct"] = monthly_data[
    "month_start"].dt.to_period("M").map(inflation_by_month)

# Adding lag features (For previous week sales)
monthly_data = monthly_data.sort_values(["store_id", "product_id", "month_start"])
for column in ["revenue_kes", "units_sold", "transaction_count"]:
    monthly_data[f"previous_{column}"] = (
        monthly_data.groupby(["store_id", "product_id"])[column].shift(1))

In [ ]:
#Arranging and viewing weekly columns
feature_columns = ["year", "month", "end_month_indicator",
    "store_id", "product_id", "category", "promotion_indicator", 
    "discount_pct", "inflation_12m_pct", "is_holiday","previous_revenue_kes", 
    "previous_units_sold","previous_transaction_count"]

target_columns = ["revenue_kes", "units_sold", "transaction_count"]
weekly_data = weekly_data[["week_start"] + feature_columns + target_columns]

weekly_data.head()

,week_start,year,month,end_month_indicator,store_id,product_id,category,promotion_indicator,discount_pct,inflation_12m_pct,is_holiday,previous_revenue_kes,previous_units_sold,previous_transaction_count,revenue_kes,units_sold,transaction_count
0,2024-09-30,2024,9,1,S01,SKU0002,Food Staples,1,13.333333,NaN,0,NaN,NaN,NaN,8314.2,67,33
1181,2024-10-07,2024,10,0,S01,SKU0002,Food Staples,1,26.976744,2.72,1,8314.2,67.0,33.0,14095.4,127,43
2346,2024-10-14,2024,10,0,S01,SKU0002,Food Staples,0,0.000000,2.72,1,14095.4,127.0,43.0,6407.0,43,16
3515,2024-10-21,2024,10,0,S01,SKU0002,Food Staples,0,0.000000,2.72,1,6407.0,43.0,16.0,11473.0,77,35
4703,2024-10-28,2024,10,1,S01,SKU0002,Food Staples,0,0.000000,2.72,0,11473.0,77.0,35.0,14900.0,100,56

In [ ]:
#Arranging and viewing monthly columns
feature_columns = ["year", "month","store_id", "product_id", "category", 
                   "promotion_indicator", "discount_pct", "inflation_12m_pct", 
                   "is_holiday","previous_revenue_kes", "previous_units_sold",
                   "previous_transaction_count"]

target_columns = ["revenue_kes", "units_sold", "transaction_count"]
monthly_data = monthly_data[["month_start"] + feature_columns + target_columns]

monthly_data.head()

,month_start,year,month,store_id,product_id,category,promotion_indicator,discount_pct,inflation_12m_pct,is_holiday,previous_revenue_kes,previous_units_sold,previous_transaction_count,revenue_kes,units_sold,transaction_count
0,2024-10-01,2024,10,S01,SKU0002,Food Staples,1,10.526316,2.72,1,NaN,NaN,NaN,46994.6,359,152
1232,2024-11-01,2024,11,S01,SKU0002,Food Staples,1,3.351955,2.75,0,46994.6,359.0,152.0,49244.5,345,179
2464,2024-12-01,2024,12,S01,SKU0002,Food Staples,1,1.941748,2.99,1,49244.5,345.0,179.0,62282.0,429,206
3697,2025-01-01,2025,1,S01,SKU0002,Food Staples,0,0.000000,3.28,1,62282.0,429.0,206.0,30098.0,202,113
4931,2025-02-01,2025,2,S01,SKU0002,Food Staples,1,4.608939,3.45,0,30098.0,202.0,113.0,48216.4,341,179